"use client";
import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import styles from "./page.module.css";
import { useSelector } from "react-redux";
import { useRouter } from "next/navigation";
import Header from "@/components/header";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
 
      <div className="row stats my-5">
      <div className="col-2">
      <div className="card">
      <div className="card-body text-center text-success">
       
      <Link href="/CreateQA" passHref={true} >
      <div className="card-title">
        <h4 className="text-dark">CreateQA</h4>
        </div>
     
      </Link>
      </div>
      </div>
      </div>
    
      </div>
 
    </>
  );
}
