"use client";
import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import styles from "./page.module.css";
import { useSelector } from "react-redux";
import { useRouter } from "next/navigation";
import Header from "@/components/header";
import { Inter } from "next/font/google";
import Table from "@/components/table";
import ActivityLog from "@/components/table/ActivityLog";
import React from "react";
const inter = Inter({ subsets: ["latin"] });

interface ID {
  id: number
}

export default function Dashboard() {
  const [idnumber, setidnumber] = React.useState<ID>({
    id:0
  })
  return (
    <>
      {/* <ActivityLog id={idnumber.id} /> */}
      {/* <ActivityLog/> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="row55 stats55 my-0 h-[90vh] pt-[0rem]">
        <div className=" ms-2" style={{ height: "0rem" }}>
          <Link href="/CreateQA" passHref={true}>
            <button className="btn btn-light btn-lg float-end m-4 me-5 px-5 bg-#6d7fcc" style={{ backgroundColor: '#263c9c', color: 'white' }}>Create QA</button>
          </Link>
          <h2 className="m-4 text-[2rem]">Project Details</h2>
          {/* <div className="card">
            <div className="card-body text-center text-success">
              <Link href="/CreateQA" passHref={true}>
                <div className="card-title">
                  <h4 className="text-dark">CreateQA</h4>
                </div>
                <button className="btn">CreateQA</button>
              </Link>
            </div>
          </div> */}
        </div>
        <div className="" style={{
          borderRadius: "2%",
          backgroundColor: "transparent", width: "92%", height: "25.5rem", marginLeft: "35px", marginRight: "9", marginTop: "8%", padding: "0rem"
        }}>
          <Table />
        </div>
      </div>
    </>
  );
}
